### ISSUE TITLE
uninitialized constant FastExcel::WorkbookExt::Set

### ISSUE THREAD

**Issue by AdditionalTesting** [Paxa/fast_excel#26]
Whenever I try to run the first command in your example I get this error.
*uninitialized constant FastExcel::WorkbookExt::Set*

This is the variable assignment i am attempting 
*workbook = FastExcel.open("hello_world_ffi.xlsx", constant_memory: true)*

*NameError: uninitialized constant FastExcel::WorkbookExt::Set
	from /home/alb/.rvm/gems/ruby-2.3.5/gems/fast_excel-0.2.5/lib/fast_excel.rb:326:in `initialize'
	from /home/alb/.rvm/gems/ruby-2.3.5/gems/fast_excel-0.2.5/lib/fast_excel.rb:35:in `new'
	from /home/alb/.rvm/gems/ruby-2.3.5/gems/fast_excel-0.2.5/lib/fast_excel.rb:35:in `open'
	from (irb):33
	from /usr/share/rvm/rubies/ruby-2.3.5/bin/irb:11:in `<main>'*

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/fast_excel/commit/85e211346ce6f7aff5cdc9170bc68061a664dd85
